# -*- coding: utf-8 -*-
"""Semantic search

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14b_ff-yxm9owKs6UxGumJQKphQK1pUl0
"""

!pip install sentence_transformers

import sentence_transformers
import numpy as np

corpus = ["A man is eating food.",
          "A man is eating a piece of bread.",
          "The girl is carrying a baby.",
          "A man is riding a horse.",
          "A woman is playing violin.",
          "Two men pushed carts through the woods.",
          "A man is riding a white horse on an enclosed ground.",
          "A monkey is playing drums.",
          "A cheetah is running behind its prey."]

model = "paraphrase-multilingual-MiniLM-L12-v2"
embedder = sentence_transformers.SentenceTransformer(model)

corpus_embeddings = embedder.encode(corpus)

def query(embedder, corpus, query, top_k=5):
  query_embedding = embedder.encode([query])
  cos_scores = sentence_transformers.util.pytorch_cos_sim(query_embedding, corpus_embeddings)[0]
  cos_scores = cos_scores.cpu()
  top_results = np.argpartition(-cos_scores, range(top_k)) [0:top_k]
  print("\nQuery:", query)
  for idx in top_results[0:top_k]:
    print(corpus[idx].strip(), "Score: %.4f" % (cos_scores[idx]))

query(embedder, corpus, "A man is eating pasta.")

query(embedder, corpus, "Someone in a gorilla costume is paying a set of drums.")

query(embedder, corpus, "Un hombre está comiendo pasta.")

query(embedder, corpus, "Ένα κορίτσι ταξιδεύει με αυτοκίνητο.")