# -*- coding: utf-8 -*-
"""02_CÓDIGO_TrinadoJiménez_Prácticafinal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sw3bUZGU--sbtW66UJHkBq8Rcax8Ljc_
"""

import pandas as pd
from google.colab import drive
import os
from bs4 import BeautifulSoup
from google.colab import drive
drive.mount("/content/gdrive")

!ls "/content/gdrive/MyDrive/Colab Notebooks/TRINADOJIMÉNEZ_PRÁCTICAFINAL/01_CORPUS"

dataset_folder = "/content/gdrive/MyDrive/Colab Notebooks/TRINADOJIMÉNEZ_PRÁCTICAFINAL/01_CORPUS"

joyeria_keywords = ["joya", "joyería", "oro", "plata", "platería", "orfebrería", "platero", "orfebre", "gema", "metal precioso",
    "anillo", "colgante", "cruz", "relicario", "pendiente", "broche", "plata sobredorada", "cincel", "sobrepujada"]

file_paths = ["/content/gdrive/MyDrive/Colab Notebooks/TRINADOJIMÉNEZ_PRÁCTICAFINAL/01_CORPUS/Museo Nacional Centro de Arte Reina Sofía.html", "/content/gdrive/MyDrive/Colab Notebooks/TRINADOJIMÉNEZ_PRÁCTICAFINAL/01_CORPUS/Museo Nacional del Prado.html", "/content/gdrive/MyDrive/Colab Notebooks/TRINADOJIMÉNEZ_PRÁCTICAFINAL/01_CORPUS/Portada - Museo Nacional de Artes Decorativas _ Ministerio de Cultura.html"]
for root, dirs, files in os.walk(dataset_folder):
    for file in files:
        if file.endswith(".html"):
            file_path = os.path.join(root, file)
            file_paths.append(file_path)
def extract_text_from_html(file_path):
    with open(file_path, "r", encoding="utf-8") as file:
        soup = BeautifulSoup(file, "html.parser")
        return soup.get_text()

def classify_text(text):
    text_lower = text.lower()
    if any(keyword in text_lower for keyword in joyeria_keywords):
        return "Corpus"
    else:
        return "Otros"

results = []
for file_name in os.listdir(dataset_folder):
    if file_name.endswith(".html"):
        file_path = os.path.join(dataset_folder, file_name)
        text = extract_text_from_html(file_path)
        classification = classify_text(text)
        results.append((file_name, classification))

df_results = pd.DataFrame(results, columns=["Archivo", "Clasificación"])
print(df_results)